lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  forward "/files", Exfile.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug  DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    resources "/blog", TopicController
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack
    #get “/”, TranslitController, :index
    resources "/translit", TranslitController
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

lib/discuss_web/templates/page/index.html.eex
<div class="container">
  <div class="col-sm-5">
    <textarea rows="10" cols="200" class="form-control" id="cyrillic"></textarea>
  </div>
  <div class="col-sm-5">
    <textarea rows="10" cols="200" class="form-control" id="latin"></textarea>
  </div>

  <div class="col-sm-2">     
    <button type="button" onclick="myFunction()">Convert</button>
  </div>
</div>


<div class="row marketing">
  <h5>Upload a new file</h5>

  <%= form_for @conn, translit_path(@conn, :create), 
               [multipart: true], fn f -> %>
    <div class="form-group">
      <label>File</label>
      <%= file_input f, :file %>
      <%= error_tag f, :file %>
    </div>
    <div class="form-group">
      <%= submit "Submit", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

<script>
  function myFunction() {
      var str = document.getElementById("cyrillic").value;
      str = str.split("а").join("a").split("ә").join("á").split("б").join("b").split("в").join("v")
            .split("г").join("g").split("ғ").join("ǵ").split("д").join("d").split("е").join("e")
            .split("ё").join("e").split("э").join("e").split("ж").join("j").split("з").join("z")
            .split("и").join("ı").split("й").join("ı").split("к").join("k").split("қ").join("q")
            .split("л").join("l").split("м").join("m").split("н").join("n").split("ң").join("ń")
            .split("о").join("o").split("ө").join("ó").split("п").join("p").split("р").join("r")
            .split("с").join("s").split("т").join("t").split("у").join("ý").split("ұ").join("u")
            .split("ү").join("ú").split("ф").join("f").split("х").join("h").split("һ").join("h")
            .split("ц").join("ts").split("ч").join("ch").split("ш").join("sh").split("щ").join("sch")
            .split("ы").join("y").split("і").join("i").split("ю").join("yu").split("я").join("ya")
            .split("А").join("A").split("Ә").join("Á").split("Б").join("B").split("В").join("V")
            .split("Г").join("G").split("Ғ").join("Ǵ").split("Д").join("D").split("Е").join("E")
            .split("Ё").join("E").split("Э").join("E").split("Ж").join("J").split("З").join("Z")
            .split("И").join("I").split("Й").join("I").split("І").join("I").split("К").join("K")
            .split("Қ").join("Q").split("Л").join("L").split("М").join("M").split("Н").join("N")
            .split("Ң").join("Ń").split("О").join("O").split("Ө").join("Ó").split("П").join("P")
            .split("Р").join("R").split("С").join("S").split("Т").join("T").split("У").join("Ý")
            .split("Ұ").join("U").split("Ү").join("Ú").split("Ф").join("F").split("Х").join("H")
            .split("Һ").join("H").split("Ц").join("Ts").split("Ч").join("Ch").split("Ш").join("Sh")
            .split("Щ").join("Sch").split("Ы").join("Y").split("Ю").join("Yu").split("Я").join("Ya");

      document.getElementById("latin").value = str;
  }
</script>