lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  forward "/files", Exfile.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug  DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    resources "/blog", TopicController
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack
    #get “/”, TranslitController, :index
    resources "/translit", TranslitController
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Transliterator</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>

  <body>

    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="/" class="brand-logo">Transliterator</a>
        <!--ul class="right hide-on-med-and-down">
          <li>
            <%= if @conn.assigns[:user] do %>
              <li>
              <%= link "Sign Out", to: auth_path(@conn, :signout) %>
              </li>
            <% else %>
              <li>
                <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
              </li>
            <% end %>
          </li>
        </ul-->

        <ul id="nav-mobile" class="sidenav">
          <li><a href="#">Navbar Link</a></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
    </nav>
    <br/>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  </body>
</html>